Check element loading
Tanaguru/tanaguru2020-engine pull request #29
Opened 2021-01-15 08:46 UTC by lpedrau

2021-01-15 15:36 UTC, rcharre requested changes

2021-01-15 15:36 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/domain/constant/EAuditParameter.java
> +    CSS_QUERY;
CSS QUERY c'est un peu trop vague comme nom, quelqu'un entrant sur le projet pourrait ne pas comprendre de quoi il s'agit.

2021-01-18 09:30 UTC, lpedrau commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/domain/constant/EAuditParameter.java
> +    CSS_QUERY;
CSS_SELECTOR_LOADING_PAGE c'est mieux par exemple ? Je ne vois pas trop quoi mettre comme nom plus explicite

2021-01-18 10:13 UTC, lpedrau commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/domain/constant/EAuditParameter.java
> +    CSS_QUERY;
j'ai changé par CSS_QUERY_ON_LOADED_PAGE pour que ce soit + précis

2021-01-20 14:11 UTC, rcharre requested changes

2021-01-20 14:11 UTC, rcharre commented on tanaguru-engine/tanaguru-audit-runner/src/main/java/com/tanaguru/runner/AbstractAuditRunner.java
> +                }
Il faut mettre ce bout de code dans la fonction webdriverGet

2021-03-01 11:18 UTC, rcharre requested changes

2021-03-01 11:18 UTC, rcharre commented on CHANGELOG.md
> +- Possibility to check the loading of a page with the search of a css selector
On est passé en 1.0.3

2021-03-01 12:36 UTC, lpedrau commented on CHANGELOG.md
> +- Possibility to check the loading of a page with the search of a css selector
ah oui, modif faite

2022-01-13 09:41 UTC, closed without merging