Stats endpoints
Tanaguru/tanaguru2020-engine pull request #71
Opened 2021-05-19 07:54 UTC by lpedrau

2021-06-04 12:41 UTC, rcharre requested changes

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/repository/StatusResultRepository.java
> +    Optional<Integer> getSumNumberOfErrorsForPages(@Param("ids") List<Long> pageIdList);
Ca ne devrait pas etre des optional ca si il n'y a aucun statusResult la moyenne devrait etre 0

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/StatsServiceImpl.java
> +		});
Mauvaise utilisation des streams.
exemple de début : 
auditStream.stream
   .map(Audit::getPages())
   .map(Page::getId())
   ....
Utilise reduce pour faire ta moyenne

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/StatsServiceImpl.java
> +		return (double) (nbAudits/nbAuditsList.size());
Utilise map reduce

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/StatsServiceImpl.java
> +	    return average;
Utilise map reduce

2021-06-04 12:41 UTC, rcharre commented on tanaguru-rest/src/main/java/com/tanaguru/controller/StatsController.java
> +    }
Pourquoi retourner une chaine de caractere quand tu peux retourner l'entité qui sera automatiquement serialisée?

2021-06-04 12:41 UTC, rcharre commented on tanaguru-rest/src/main/java/com/tanaguru/controller/StatsController.java
> +
La plupart des endpoint verifie que l'utilisateur courant n'est pas null. Mais est ce que tous les utilisateurs connectés doivent y acceder ou seulement les admin / superadmin ?

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/StatsServiceImpl.java
> +	public JSONObject createStats() {
Pourquoi as tu besoin de créer un JSON object ? prefere utiliser une classe DTO  qui pourra etre documentée via springfox

2021-06-04 12:41 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/StatsServiceImpl.java
> +		return (double) (nbUsers/nbUsersList.size());
Utilise map reduce

2021-07-01 13:02 UTC, rcharre requested changes

2021-07-01 13:02 UTC, rcharre commented on tanaguru-rest/src/main/java/com/tanaguru/controller/StatsController.java
> +        return this.statsService.createStats();
Comme l'operation effectue un tres grand nombre de requete il serait preferable que les données soient aggreger un certains nombre de fois dans la journée et pas à chaque requete. 
Je te propose d'utiliser ceci : https://www.baeldung.com/spring-scheduled-tasks dans le service et de stocker le resultat des statistiques ainsi que de créer une clé de configuration permettant de choisir le temps entre chaque analyse. le service doit aussi créer ces statistique au démarrage (@postconstruct)

2021-07-07 12:12 UTC, lpedrau commented on tanaguru-rest/src/main/java/com/tanaguru/controller/StatsController.java
> +        return this.statsService.createStats();
le résultat est stocké dans une variables stats, et une clé de conf permet de choisir la durée entre chaque analyse.
avec @Scheduled sur la méthode, les statistiques sont récupérées au démarrage dans la variable, pas besoin d'ajouter @PostContruct

2021-07-08 07:58 UTC, rcharre approved these changes

2021-07-08 07:58 UTC, rcharre commented
J'attends de pouvoir valider l'image docker avant de merger

2021-07-08 09:46 UTC, merged