Endpoint result test synthesis
Tanaguru/tanaguru2020-engine pull request #90
Opened 2021-08-03 08:26 UTC by lpedrau

2021-08-03 09:39 UTC, rcharre requested changes

2021-08-03 09:39 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/TestHierarchyResultServiceImpl.java
> +
Evite au maximum d'avoir des methodes entieres ici, tu devrais extraire ca dans une methode a part.

2021-08-03 09:39 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/TestHierarchyResultServiceImpl.java
> +    private String getGlobalStatus(List<String> allStatus){
Utilise un Set plutot qu'une liste pour eviter les doublons

2021-08-03 09:39 UTC, rcharre commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/TestHierarchyResultServiceImpl.java
> +        return testStatus;
Dans de nombreux cas je suis favorable au fait de n'avoir qu'un seul return dans une methode, ici je prefere la forme suivante :

`if(....){
    return ...
}`

2021-08-03 12:06 UTC, lpedrau commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/TestHierarchyResultServiceImpl.java
> +
création d'une méthode : addInMapTestHierarchyCodeAndStatus

2021-08-03 12:07 UTC, lpedrau commented on tanaguru-engine/tanaguru-api/src/main/java/com/tanaguru/service/impl/TestHierarchyResultServiceImpl.java
> +        return testStatus;
d'accord, j'ai au final simplifié la méthode en passant par des if ( set.contains(..) ) else if .. et des return

2021-08-06 13:09 UTC, rcharre approved these changes

2021-08-06 13:09 UTC, merged